# Generated by Django 3.1.1 on 2020-09-12 21:15

from django.db import migrations, models
import patient.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('cpf', models.BigIntegerField(validators=[patient.utils.validate_cpf])),
                ('birth_date', models.DateField()),
                ('phone', models.BigIntegerField(validators=[patient.utils.validate_phone])),
            ],
        ),
    ]
