# Generated by Django 3.1.1 on 2020-09-12 22:49

from django.db import migrations, models
import django.db.models.deletion
import patient.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[patient.utils.validate_cpf])),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15, validators=[patient.utils.validate_phone])),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='address.address')),
            ],
        ),
    ]
