# Generated by Django 3.1.1 on 2020-09-12 22:08

import address.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('number', models.PositiveIntegerField()),
                ('additional_adress', models.TextField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField(validators=[address.utils.validate_zip_code])),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
    ]
